export const ACTION_STATE = 'ACTION_STATE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_FULFILLED = 'SIGNUP_FULFILLED';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';

export const GET_REFRESH_TOKEN_PENDING = 'GET_REFRESH_TOKEN_PENDING';
export const GET_REFRESH_TOKEN_FULFILLED = 'GET_REFRESH_TOKEN_FULFILLED';
export const GET_REFRESH_TOKEN_REJECTED = 'GET_REFRESH_TOKEN_REJECTED';


export const CREATE_HOTEL_PENDING = 'CREATE_HOTEL_PENDING';
export const CREATE_HOTEL_FULFILLED = 'CREATE_HOTEL_FULFILLED';
export const CREATE_HOTEL_REJECTED = 'CREATE_HOTEL_REJECTED';

export const GET_HOTEL_DATA_PENDING = 'GET_HOTEL_DATA_PENDING';
export const GET_HOTEL_DATA_FULFILLED = 'GET_HOTEL_DATA_FULFILLED';
export const GET_HOTEL_DATA_REJECTED = 'GET_HOTEL_DATA_REJECTED';

export const DELETE_HOTEL_DATA_PENDING = 'DELETE_HOTEL_DATA_PENDING';
export const DELETE_HOTEL_DATA_FULFILLED = 'DELETE_HOTEL_DATA_FULFILLED';
export const DELETE_HOTEL_DATA_REJECTED = 'DELETE_HOTEL_DATA_REJECTED';


export const VALIDATE_TOKEN_PENDING = 'VALIDATE_TOKEN_PENDING';
export const VALIDATE_TOKEN_FULFILLED = 'VALIDATE_TOKEN_FULFILLED';
export const VALIDATE_TOKEN_REJECTED = 'VALIDATE_TOKEN_REJECTED';

export const GET_PLANS_DATA_PENDING = 'GET_PLANS_DATA_PENDING';
export const GET_PLANS_DATA_FULFILLED = 'GET_PLANS_DATA_FULFILLED';
export const GET_PLANS_DATA_REJECTED = 'GET_PLANS_DATA_REJECTED';

export const GET_REVIEWS_DATA_PENDING = 'GET_REVIEWS_DATA_PENDING';
export const GET_REVIEWS_DATA_FULFILLED = 'GET_REVIEWS_DATA_FULFILLED';
export const GET_REVIEWS_DATA_REJECTED = 'GET_REVIEWS_DATA_REJECTED';

