export const ACTION_STATE = 'ACTION_STATE';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_FULFILLED = 'SIGNUP_FULFILLED';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';

export const GET_REFRESH_TOKEN_PENDING = 'GET_REFRESH_TOKEN_PENDING';
export const GET_REFRESH_TOKEN_FULFILLED = 'GET_REFRESH_TOKEN_FULFILLED';
export const GET_REFRESH_TOKEN_REJECTED = 'GET_REFRESH_TOKEN_REJECTED';


export const CREATE_HOTEL_PENDING = 'CREATE_HOTEL_PENDING';
export const CREATE_HOTEL_FULFILLED = 'CREATE_HOTEL_FULFILLED';
export const CREATE_HOTEL_REJECTED = 'CREATE_HOTEL_REJECTED';

export const GET_HOTEL_DATA_PENDING = 'GET_HOTEL_DATA_PENDING';
export const GET_HOTEL_DATA_FULFILLED = 'GET_HOTEL_DATA_FULFILLED';
export const GET_HOTEL_DATA_REJECTED = 'GET_HOTEL_DATA_REJECTED';

export const DELETE_HOTEL_DATA_PENDING = 'DELETE_HOTEL_DATA_PENDING';
export const DELETE_HOTEL_DATA_FULFILLED = 'DELETE_HOTEL_DATA_FULFILLED';
export const DELETE_HOTEL_DATA_REJECTED = 'DELETE_HOTEL_DATA_REJECTED';


export const VALIDATE_TOKEN_PENDING = 'VALIDATE_TOKEN_PENDING';
export const VALIDATE_TOKEN_FULFILLED = 'VALIDATE_TOKEN_FULFILLED';
export const VALIDATE_TOKEN_REJECTED = 'VALIDATE_TOKEN_REJECTED';

export const GET_PLANS_DATA_PENDING = 'GET_PLANS_DATA_PENDING';
export const GET_PLANS_DATA_FULFILLED = 'GET_PLANS_DATA_FULFILLED';
export const GET_PLANS_DATA_REJECTED = 'GET_PLANS_DATA_REJECTED';

export const GET_REVIEWS_DATA_PENDING = 'GET_REVIEWS_DATA_PENDING';
export const GET_REVIEWS_DATA_FULFILLED = 'GET_REVIEWS_DATA_FULFILLED';
export const GET_REVIEWS_DATA_REJECTED = 'GET_REVIEWS_DATA_REJECTED';

export const UPDATE_PLATFORMS_STATUS_PENDING = 'UPDATE_PLATFORMS_STATUS_PENDING';
export const UPDATE_PLATFORMS_STATUS_FULFILLED = 'UPDATE_PLATFORMS_STATUS_FULFILLED';
export const UPDATE_PLATFORMS_STATUS_REJECTED = 'UPDATE_PLATFORMS_STATUS_REJECTED';

export const GET_BAR_DATA_PENDING = 'GET_BAR_DATA_PENDING';
export const GET_BAR_DATA_FULFILLED = 'GET_BAR_DATA_FULFILLED';
export const GET_BAR_DATA_REJECTED = 'GET_BAR_DATA_REJECTED';

export const GET_LINE_ONE_DATA_PENDING = 'GET_LINE_ONE_DATA_PENDING';
export const GET_LINE_ONE_DATA_FULFILLED = 'GET_LINE_ONE_DATA_FULFILLED';
export const GET_LINE_ONE_DATA_REJECTED = 'GET_LINE_ONE_DATA_REJECTED';

export const GET_LINE_TWO_DATA_PENDING = 'GET_LINE_TWO_DATA_PENDING';
export const GET_LINE_TWO_DATA_FULFILLED = 'GET_LINE_TWO_DATA_FULFILLED';
export const GET_LINE_TWO_DATA_REJECTED = 'GET_LINE_TWO_DATA_REJECTED';

export const GET_DASHBOARD_COUNT_DATA_PENDING = 'GET_DASHBOARD_COUNT_DATA_PENDING';
export const GET_DASHBOARD_COUNT_DATA_FULFILLED = 'GET_DASHBOARD_COUNT_DATA_FULFILLED';
export const GET_DASHBOARD_COUNT_DATA_REJECTED = 'GET_DASHBOARD_COUNT_DATA_REJECTED';

export const UPDATE_HOTEL_DATA_PENDING = "UPDATE_HOTEL_DATA_PENDING";
export const UPDATE_HOTEL_DATA_FULFILLED = "UPDATE_HOTEL_DATA_FULFILLED";
export const UPDATE_HOTEL_DATA_REJECTED = "UPDATE_HOTEL_DATA_REJECTED";

export const GET_ACTIVE_PLAN_PENDING = "GET_ACTIVE_PLAN_PENDING";
export const GET_ACTIVE_PLAN_FULFILLED = "GET_ACTIVE_PLAN_FULFILLED";
export const GET_ACTIVE_PLAN_REJECTED = "GET_ACTIVE_PLAN_REJECTED";

export const SELECT_PLAN_PENDING = "SELECT_PLAN_PENDING";
export const SELECT_PLAN_FULFILLED = "SELECT_PLAN_FULFILLED";
export const SELECT_PLAN_REJECTED = "SELECT_PLAN_REJECTED";

export const HANDLE_BILLING_PAGE_PENDING = "HANDLE_BILLING_PAGE_PENDING";
export const HANDLE_BILLING_PAGE_FULFILLED = "HANDLE_BILLING_PAGE_FULFILLED";
export const HANDLE_BILLING_PAGE_REJECTED = "HANDLE_BILLING_PAGE_REJECTED";
